Update GEOS-Chem Users page for registrations between June-Sept 2024
geoschem/geoschem.github.io pull request #38
Opened 2024-10-02 14:37 UTC by msulprizio

### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard

### Describe the update

The GEOS-Chem users page has now been updated using the registered-users.xlsx dataset from AWS. This contains the registration information that users enter upon first creation of a GCClassic or GCHP run directory.

2024-10-02 19:26 UTC, yantosca requested changes
Thanks @msulprizio!  I noted a few minor issues to be resolved.  Otherwise it looks great!

2024-10-03 18:37 UTC, msulprizio commented on users.html
> +  L.marker([14.078499986291364, 100.61398255227519], { icon: blueIcon }).addTo(mymap).bindPopup("<strong>Asian Institute of Technology</strong><br>Pathum Thani, Thailand<ul><li><a href='https://ait.a
Yes, that is correct. That is the link the team provided.

2024-10-03 18:46 UTC, msulprizio commented on users.html
> +  // Delft University of Technology
Thanks. I have updated to the group page for Aircraft Noise and Climate Effects: https://www.tudelft.nl/lr/organisatie/afdelingen/control-and-operations/aircraft-noise-and-climate-effects-ance.

2024-10-03 18:46 UTC, msulprizio commented on users.html
> +  L.marker([48.8483238, 2.34308173439024], { icon: blueIcon }).addTo(mymap).bindPopup("<strong>Sorbonne Université</strong><br>Paris, France<ul><li><a href='https://www.sorbonne-universite.fr/' targe
Now fixed in https://github.com/geoschem/geoschem.github.io/pull/38/commits/c8adbba7c7d4f454da668e86a04a155a788814f6

2024-10-03 18:47 UTC, msulprizio commented on users.html
> +
Link now updated in https://github.com/geoschem/geoschem.github.io/pull/38/commits/c8adbba7c7d4f454da668e86a04a155a788814f6

2024-10-03 18:47 UTC, msulprizio commented on users.html
> +  L.marker([53.89219072719476, -122.81330705805765], { icon: blueIcon }).addTo(mymap).bindPopup("<strong>University of British Columbia</strong><br>Prince George, British Columbia, Canada</strong><ul
Thanks. Copy and paste error. Now fixed in https://github.com/geoschem/geoschem.github.io/pull/38/commits/c8adbba7c7d4f454da668e86a04a155a788814f6.

2024-10-03 18:47 UTC, msulprizio commented on users.html
> +  L.marker([20.29698158118392, 85.84044738036371], { icon: blueIcon }).addTo(mymap).bindPopup("<strong>Utkal University</strong><br>Bhubaneswar, Odisha, India<ul><li><a href='https://utkaluniversity.
Yes, it seems something is down on their end. Even the main university website won't load.

2024-10-03 18:51 UTC, yantosca approved these changes
Thanks @msulprizio.  Good to merge!

2024-10-03 19:00 UTC, merged